name: TaskManager CI

on:
  push:
    branches:
      - master
  release:
    types: [ published, created, edited ]
permissions:
  packages: write

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: chmod +x gradlew
        run: chmod +x gradlew
      - name: Check Style
        run: ./gradlew ktlintCheck
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: chmod +x gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
